// Generated by Haxe 4.1.2
(function ($global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var GameScene = function() {
	this.bricks = [];
	this.isAlreadyCollided = false;
	Phaser.Scene.call(this,{ init : $bind(this,this.init), preload : $bind(this,this.preload), create : $bind(this,this.create), update : $bind(this,this.update)});
};
GameScene.__super__ = Phaser.Scene;
GameScene.prototype = $extend(Phaser.Scene.prototype,{
	init: function() {
		this.scale.setZoom(2);
		this.keys = this.input.keyboard.addKeys({ "left" : "left", "right" : "right", "a" : "A", "d" : "D"});
	}
	,preload: function() {
		this.load.image("paddle","res/paddle.png");
		this.load.image("brick","res/brick.png");
		this.load.image("ball","res/ball.png");
		this.load.image("pixel","res/pixel.png");
	}
	,create: function() {
		this.textBricks = this.add.text(4,34,"",{ fontFamily : "Georgia, \"Goudy Bookletter 1911\", Times, serif"});
		this.textDirAndDist = this.add.text(4,44,"",{ fontFamily : "Georgia, \"Goudy Bookletter 1911\", Times, serif"});
		this.paddle = this.add.sprite(0,0,"paddle").setOrigin(0.5,0).setDepth(2);
		this.physics.world.enable(this.paddle);
		this.ball = this.add.sprite(0,0,"ball").setDepth(1);
		this.physics.world.enable(this.ball);
		this.paddleEmitter = this.add.particles("pixel").createEmitter({ scale : { start : 5, end : 0}, speed : 4, lifespan : 450, follow : this.paddle, followOffset : { x : 0, y : 0}}).stop();
		this.newGame();
	}
	,newGame: function() {
		this.paddle.setPosition(70,86);
		this.paddleVecX = 0;
		this.paddleEmitter.stop();
		this.ball.setPosition(70,70);
		var angle = -1.57 + (Math.random() - 0.5) * 2;
		this.ballDirX = Math.cos(angle);
		this.ballDirY = Math.sin(angle);
		this.ballSpeed = 1;
		this.recreateBricks();
	}
	,update: function(d0,d01) {
		this.movePaddle();
		this.collideBallWithWalls();
		this.collideBallWithBricks();
		this.collideBallWithPaddle();
	}
	,movePaddle: function() {
		if(this.keys.left.isDown || this.keys.a.isDown) {
			if(this.paddleVecX == 0) {
				this.paddleEmitter.start();
			}
			this.paddleVecX -= 1;
		}
		if(this.keys.right.isDown || this.keys.d.isDown) {
			if(this.paddleVecX == 0) {
				this.paddleEmitter.start();
			}
			this.paddleVecX += 1;
		}
		if(this.paddleVecX < -3) {
			this.paddleVecX = -3;
		}
		if(this.paddleVecX > 3) {
			this.paddleVecX = 3;
		}
		this.paddle.x += this.paddleVecX;
		if(this.paddle.x < 8) {
			this.paddle.x = 8;
		} else if(this.paddle.x > 132) {
			this.paddle.x = 132;
		}
		if(this.paddleVecX < 0) {
			this.paddleVecX += 0.2;
			if(this.paddleVecX > 0) {
				this.paddleVecX = 0;
			}
			if(this.paddleVecX == 0) {
				this.paddleEmitter.stop();
			}
		} else if(this.paddleVecX > 0) {
			this.paddleVecX -= 0.2;
			if(this.paddleVecX < 0) {
				this.paddleVecX = 0;
			}
			if(this.paddleVecX == 0) {
				this.paddleEmitter.stop();
			}
		}
	}
	,collideBallWithWalls: function() {
		this.ball.x += this.ballDirX * this.ballSpeed;
		this.ball.y += this.ballDirY * this.ballSpeed;
		if(this.ball.x < 7) {
			this.ball.x = 7;
			this.ballDirX = -this.ballDirX;
		} else if(this.ball.x > 133) {
			this.ball.x = 133;
			this.ballDirX = -this.ballDirX;
		}
		if(this.ball.y < 7) {
			this.ball.y = 7;
			this.ballDirY = -this.ballDirY;
		} else if(this.ball.y > 100) {
			this.ball.y = 100;
			this.ballDirY = -this.ballDirY;
			this.gameOver();
		}
	}
	,collideBallWithPaddle: function() {
		var _gthis = this;
		var currentTickCollided = false;
		this.physics.overlap(this.ball,this.paddle,function() {
			currentTickCollided = true;
			if(!_gthis.isAlreadyCollided) {
				_gthis.isAlreadyCollided = true;
				var dirAndDist = _gthis.ball.x - _gthis.paddle.x;
				_gthis.textDirAndDist.setText(dirAndDist);
				if(dirAndDist > -12 && dirAndDist < 12) {
					if(_gthis.ball.y + _gthis.ball.height / 2 < _gthis.paddle.y + 5) {
						var hitAngle = Math.atan2(_gthis.ballDirY,_gthis.ballDirX);
						var shiftAngle = -hitAngle + dirAndDist / 14;
						console.log("src/arkanoid/GameScene.hx:137:","hitAngle: " + hitAngle + ", dirAndDist: " + dirAndDist + ", shiftAngle: " + shiftAngle);
						_gthis.ballDirX = Math.cos(shiftAngle);
						_gthis.ballDirY = Math.sin(shiftAngle);
					}
				} else {
					console.log("src/arkanoid/GameScene.hx:144:","おねがい");
					if(dirAndDist < 0) {
						if(_gthis.ballDirX > 0) {
							_gthis.ballDirX = -_gthis.ballDirX;
						}
					} else if(_gthis.ballDirX < 0) {
						_gthis.ballDirX = -_gthis.ballDirX;
					}
				}
			}
		});
		if(!currentTickCollided) {
			this.isAlreadyCollided = false;
		}
	}
	,gameOver: function() {
		this.newGame();
	}
	,recreateBricks: function() {
		var _g = 0;
		var _g1 = this.bricks;
		while(_g < _g1.length) {
			var brick = _g1[_g];
			++_g;
			this.physics.world.disable(brick);
			brick.destroy();
		}
		this.bricks.length = 0;
		var map = [[1,1,1,1,1,1,1],[1,1,1,1,1,1,1],[1,1,1,1,1,1,1],[1,1,1,1,1,1,1],[1,1,0,0,0,1,1],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0],[1,1,0,0,0,1,1],[1,1,0,0,0,1,1]];
		var _g = 0;
		var _g1 = map.length;
		while(_g < _g1) {
			var iy = _g++;
			var _g2 = 0;
			var _g3 = map[0].length;
			while(_g2 < _g3) {
				var ix = _g2++;
				if(map[iy][ix] == 0) {
					continue;
				}
				var brick = this.add.sprite(0,0,"brick").setPosition(16 + ix * 18,8 + iy * 7);
				this.physics.world.enable(brick);
				this.bricks.push(brick);
			}
		}
		this.textBricks.setText(this.bricks.length);
	}
	,collideBallWithBricks: function() {
		var _gthis = this;
		var forRemove = [];
		var _g = 0;
		var _g1 = this.bricks;
		while(_g < _g1.length) {
			var brick = [_g1[_g]];
			++_g;
			this.physics.collide(this.ball,brick[0],(function(brick) {
				return function() {
					var brickHitAngle = Math.atan2(_gthis.ball.y - brick[0].y,_gthis.ball.x - brick[0].x);
					if(brickHitAngle >= -2.78 && brickHitAngle < -0.36) {
						if(_gthis.ballDirY > 0) {
							_gthis.ballDirY = -_gthis.ballDirY;
						}
					} else if(brickHitAngle >= -0.36 && brickHitAngle < 0.36) {
						if(_gthis.ballDirX < 0) {
							_gthis.ballDirX = -_gthis.ballDirX;
						}
					} else if(brickHitAngle >= 0.36 && brickHitAngle < 2.78) {
						if(_gthis.ballDirY < 0) {
							_gthis.ballDirY = -_gthis.ballDirY;
						}
					} else if(brickHitAngle >= 2.78 || brickHitAngle < -2.78) {
						if(_gthis.ballDirX > 0) {
							_gthis.ballDirX = -_gthis.ballDirX;
						}
					}
					forRemove.push(brick[0]);
				};
			})(brick));
		}
		var _g = 0;
		while(_g < forRemove.length) {
			var brick1 = forRemove[_g];
			++_g;
			HxOverrides.remove(this.bricks,brick1);
			brick1.destroy();
			this.textBricks.setText(this.bricks.length);
			if(this.bricks.length == 0) {
				window.alert("Great Job！！あなたはSEXY");
			}
		}
	}
});
var HxOverrides = function() { };
HxOverrides.remove = function(a,obj) {
	var i = a.indexOf(obj);
	if(i == -1) {
		return false;
	}
	a.splice(i,1);
	return true;
};
HxOverrides.now = function() {
	return Date.now();
};
var Main = function() { };
Main.main = function() {
	var config = { width : 140, height : 100, type : Phaser.AUTO, render : { pixelArt : true, antialias : false}, physics : { "default" : "arcade", arcade : { debug : false}}, scene : new GameScene()};
	new Phaser.Game(config);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var $_;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
$global.$haxeUID |= 0;
if(typeof(performance) != "undefined" ? typeof(performance.now) == "function" : false) {
	HxOverrides.now = performance.now.bind(performance);
}
Main.main();
})(typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
